"""Generate promptfooconfig.yaml from fixtures/tickets.json (single source of truth).

Run after editing tickets.json:  python3 scripts/gen_promptfoo_config.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
tickets = json.loads((ROOT / "fixtures" / "tickets.json").read_text())

header = """\
# Generated by scripts/gen_promptfoo_config.py from fixtures/tickets.json. Do not hand-edit.
description: Support-ticket classifier prompt regression suite
prompts:
  - file://prompts/classify.txt
providers:
  - id: file://providers/replay_provider.py
    label: replay (recorded responses, no live API calls)
tests:
"""

lines = [header]
for t in tickets:
    cat_expr = f'json.loads(output)["category"] == "{t["expected_category"]}"'
    pri_expr = f'json.loads(output)["priority"] == "{t["expected_priority"]}"'
    lines.append(f"""  - vars:
      id: "{t['id']}"
      ticket_text: {json.dumps(t['text'])}
    assert:
      - type: is-json
      - type: python
        value: '{cat_expr}'
      - type: python
        value: '{pri_expr}'
""")

(ROOT / "promptfooconfig.yaml").write_text("".join(lines))
print(f"wrote promptfooconfig.yaml with {len(tickets)} test cases")
