"""Local-only: regenerate fixtures/recorded_responses.json against the live Anthropic API.

Never run in CI (costs money, needs ANTHROPIC_API_KEY). Run this after editing
prompts/classify.txt or fixtures/tickets.json, review the diff, then commit.

Usage: python3 scripts/record.py
"""
import datetime
import json
from pathlib import Path

import anthropic

ROOT = Path(__file__).parent.parent
MODEL = "claude-haiku-4-5"

client = anthropic.Anthropic()
prompt_template = (ROOT / "prompts" / "classify.txt").read_text()
tickets = json.loads((ROOT / "fixtures" / "tickets.json").read_text())

recorded = {
    "_meta": {
        "model": MODEL,
        "prompt_version": "classify.txt@v1",
        "recorded_at": datetime.date.today().isoformat(),
        "note": "Regenerated by scripts/record.py against the live API. CI replays this file, it never calls the API.",
    }
}

for t in tickets:
    prompt = prompt_template.replace("{{ticket_text}}", t["text"])
    response = client.messages.create(
        model=MODEL,
        max_tokens=256,
        messages=[{"role": "user", "content": prompt}],
    )
    text = "".join(b.text for b in response.content if b.type == "text").strip()
    try:
        parsed = json.loads(text)
    except json.JSONDecodeError:
        print(f"WARNING: {t['id']} did not return valid JSON: {text!r}")
        continue
    recorded[t["id"]] = {"category": parsed.get("category"), "priority": parsed.get("priority")}
    print(f"{t['id']}: {recorded[t['id']]}")

(ROOT / "fixtures" / "recorded_responses.json").write_text(json.dumps(recorded, indent=2) + "\n")
print(f"\nwrote {len(recorded) - 1} recorded responses")
